algoritmo "semnome"
// Função :
// Autor :
// Data : 23/04/2025
// Seção de Declarações 
var

hrst: inteiro
vh: real

inicio
// Seção de Comandos 
 funcao calcsals(aa: inteiro; bb: real):real
  var
    sals: real
  inicio
  sals <-aa*bb

 retorne sals
 fimfuncao

 escreva ("Informe o número de horas trabalhadas: ")
 leia (hrst)
 escreva ("Informe o valor da hora: ")
 leia (vh)

 escreval ("O salário é: ", calcsals(hrst,vh)

fimalgoritmo
