algoritmo "semnome"
// Função :
// Autor :
// Data : 23/04/2025
// Seção de Declarações 
var

num, bb: inteiro
inicio
funcao returns(aa: inteiro):inteiro
  var nums:inteiro

  inicio
  nums <- aa+ 2
  
retorne nums
fimfuncao

escreva ("Digite um número inteiro qualquer: ")
leia (num)
escreval ("Chamando a função returns: ")
bb <- returns(num)

escreval ("retorno: ", bb)

fimalgoritmo
