algoritmo "semnome"
// Função :
// Autor :
// Data : 23/04/2025
// Seção de Declarações 

inicio
// Seção de Comandos
procedimento calcidads()

var

anonas, anoatt, idads: inteiro

inicio
  escreva ("Informe o ano de nascimento: ")
  leia (anonas)
  escreva ("Informe o ano atual: ")
  leia (anoatt)

 idads <- anoatt-anonas

  escreval ("A idade em anos corresponde à: ", idads)
fimprocedimento

calcidads()

fimalgoritmo
