algoritmo "vetor exemplo 2"
// Função :
// Autor :
// Data : 16/04/2025
// Seção de Declarações 
var

num: vetor[1..5] de inteiro
cont: inteiro

inicio
// Seção de Comandos 

  para cont de 1 ate 5 faca
  escreva("Digite um número inteiro qualquer: ")
  leia (num)
  fimpara
  
  para cont de 1 ate 5 faca
  escreva("Você digitou os números: ", num)
  fimpara
  
  escreva ("O número ", num "na posição ", cont)




fimalgoritmo
