algoritmo "vetor exemplo 03"
// Função :
// Autor :
// Data : 16/04/2025
// Seção de Declarações 
var

nom: vetor[1..5] de literal
cont: inteiro

inicio
// Seção de Comandos

 para cont de 1 ate 5 faca
  escreva ("Digite um nome de usuário: ")
  leia (nom[cont])
 fimpara

 escreva ("Escolha um valor de 1 a 5: ")
 leia (cont)
 
 escreva ("O nome escolhido foi: ", nom[cont])
 
fimalgoritmo
